# Generated by Django 5.1.7 on 2025-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('data_compra', models.DateField()),
                ('data_vencimetno', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
